/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;
import Connect.MySQLConnection;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class NghiPhepNV extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public NghiPhepNV() {
        initComponents();
//        tableModel = (DefaultTableModel)DS_CaLam.getModel();
        HienThiNVCL();
        HienThiNVDTV();
        HienThiNVNP();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputMa = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableCL = new javax.swing.JTable();
        jButtonUpdate = new javax.swing.JButton();
        txtTT = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableNP = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jTableDTV = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("NGHỈ PHÉP NHÂN VIÊN");

        Exit1.setBackground(new java.awt.Color(255, 51, 51));
        Exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Mã nhân viên:");

        inputMa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaActionPerformed(evt);
            }
        });
        inputMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMaKeyPressed(evt);
            }
        });

        jTableCL.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableCL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Và Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableCL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableCLMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableCL);
        if (jTableCL.getColumnModel().getColumnCount() > 0) {
            jTableCL.getColumnModel().getColumn(1).setResizable(false);
            jTableCL.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 102));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        txtTT.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        txtTT.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Còn Làm", "Đã Thôi Việc", "Nghỉ Phép" }));
        txtTT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTTActionPerformed(evt);
            }
        });

        jTableNP.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableNP.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Và Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableNP.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableNPMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableNP);
        if (jTableNP.getColumnModel().getColumnCount() > 0) {
            jTableNP.getColumnModel().getColumn(1).setResizable(false);
            jTableNP.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jTableDTV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jTableDTV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Họ Và Tên"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableDTV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableDTVMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(jTableDTV);
        if (jTableDTV.getColumnModel().getColumnCount() > 0) {
            jTableDTV.getColumnModel().getColumn(1).setResizable(false);
            jTableDTV.getColumnModel().getColumn(1).setPreferredWidth(250);
        }

        jLabel2.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel2.setText("Nhân Viên Còn Làm");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel3.setText("Nhân Viên Đã Thôi Việc");

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 20)); // NOI18N
        jLabel5.setText("Nhân Viên Nghỉ Phép");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(546, 546, 546)
                        .addComponent(jLabel4)
                        .addGap(64, 64, 64)
                        .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addGap(100, 100, 100)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(100, 100, 100)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 320, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(126, 126, 126)
                                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(74, 74, 74)
                                .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(90, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(391, 391, 391)
                .addComponent(Exit1)
                .addGap(27, 27, 27))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(Exit1)
                        .addGap(47, 47, 47))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 357, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTT, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonUpdate))
                .addGap(61, 61, 61))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reset(){
        inputMa.setText("");

    } 
        

    private String chuyendoitrangthai(String tt){
        String TT = "";
        switch (tt){
            case "Còn làm": {TT =  "0"; break;}
            case "Đã Thôi Việc" : {TT =  "1"; break;}
            case "Nghỉ Phép": {TT =  "2"; break;}
            
        }
        return TT;
    }
    
    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void jTableCLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableCLMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableCL.getModel();

        String manv = tableModel.getValueAt(jTableCL.getSelectedRow(), 0).toString();

        inputMa.setText(manv);

    }//GEN-LAST:event_jTableCLMouseClicked

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        //lay du lieu tu bang
        String manv = String.valueOf(inputMa.getText()).trim();
        String TINHTRANG = String.valueOf(txtTT.getSelectedItem().toString().trim());
        String tinhtrang = chuyendoitrangthai(TINHTRANG);

            try {
               
                Connection con1;
                PreparedStatement insert;
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                insert = con1.prepareStatement("update nhanvien set trangthai=? where ma_nv= ?");

                insert.setString(1,tinhtrang);
                insert.setString(2,manv);

                insert.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Cập Nhật Nghỉ Phép Nhân Viên Thành Công");

                HienThiNVCL();
                HienThiNVDTV();
                HienThiNVNP();
                reset();
            } catch (Exception e) {
                e.getStackTrace();
            }
//        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed

    private void inputMaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            inputMa.setEditable(false);
        } else {
            inputMa.setEditable(true);
        }
    }//GEN-LAST:event_inputMaKeyPressed

    private void inputMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMaActionPerformed

    private void txtTTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTTActionPerformed

    private void jTableNPMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableNPMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableNP.getModel();

        String manv = tableModel.getValueAt(jTableNP.getSelectedRow(), 0).toString();

        inputMa.setText(manv);
    }//GEN-LAST:event_jTableNPMouseClicked

    private void jTableDTVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableDTVMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableDTV.getModel();

        String manv = tableModel.getValueAt(jTableDTV.getSelectedRow(), 0).toString();

        inputMa.setText(manv);
    }//GEN-LAST:event_jTableDTVMouseClicked
    
    private void HienThiNVCL() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableCL.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = null;
            cStmt = (CallableStatement) conn.prepareCall("SELECT ma_nv,ten_nv FROM `nhanvien` WHERE trangthai=0;");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String tennv = rs.getString("ten_nv");
                tableModel.addRow(new String[]{ manv, tennv});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        private void HienThiNVDTV() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableDTV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = null;
            cStmt = (CallableStatement) conn.prepareCall("SELECT ma_nv,ten_nv FROM `nhanvien` WHERE trangthai=1;");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String tennv = rs.getString("ten_nv");
                tableModel.addRow(new String[]{ manv, tennv});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
        private void HienThiNVNP() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableNP.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = null;
            cStmt = (CallableStatement) conn.prepareCall("SELECT ma_nv,ten_nv FROM `nhanvien` WHERE trangthai=2;");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String tennv = rs.getString("ten_nv");
                tableModel.addRow(new String[]{ manv, tennv});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NghiPhepNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NghiPhepNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NghiPhepNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NghiPhepNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NghiPhepNV().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit1;
    private javax.swing.JFormattedTextField inputMa;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTableCL;
    private javax.swing.JTable jTableDTV;
    private javax.swing.JTable jTableNP;
    private javax.swing.JComboBox<String> txtTT;
    // End of variables declaration//GEN-END:variables
}
