/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;
import Connect.MySQLConnection;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class ThemNV extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public ThemNV() {
        initComponents();
//        tableModel = (DefaultTableModel)DS_CaLam.getModel();
        HienThiTTNV();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        inputMa = new javax.swing.JFormattedTextField();
        jLabel3 = new javax.swing.JLabel();
        BoxMaCV = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        inputName = new javax.swing.JFormattedTextField();
        jLabel6 = new javax.swing.JLabel();
        boxNgay = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        boxThang = new javax.swing.JComboBox<>();
        boxNam = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        inputNumPhone = new javax.swing.JFormattedTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        inputAddress = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableTTNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButtonUpdate = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("QUẢN LÝ NHÂN VIÊN");

        Exit1.setBackground(new java.awt.Color(255, 51, 51));
        Exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Nhập mã nhân viên:");

        inputMa.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        inputMa.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputMa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputMaActionPerformed(evt);
            }
        });
        inputMa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputMaKeyPressed(evt);
            }
        });

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Chọn Mã Chức Vụ:");

        BoxMaCV.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BoxMaCV.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trưởng Phòng", "Nhân Viên", "Nhân Viên Lâu Năm", "Thực Tập" }));
        BoxMaCV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BoxMaCVActionPerformed(evt);
            }
        });

        jLabel5.setBackground(new java.awt.Color(102, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel5.setText("Nhập tên nhân viên:");

        inputName.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNameActionPerformed(evt);
            }
        });
        inputName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNameKeyPressed(evt);
            }
        });

        jLabel6.setBackground(new java.awt.Color(102, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Nhập ngày sinh:");

        boxNgay.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxNgay.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        boxNgay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNgayActionPerformed(evt);
            }
        });

        jLabel15.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel15.setText("Ngày");

        jLabel16.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel16.setText("Tháng");

        boxThang.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxThang.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        boxThang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxThangActionPerformed(evt);
            }
        });

        boxNam.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        boxNam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1990", "1991", "1992", "1993", "1994", "1995", "1996", "1997", "1998", "1999", "2000", "2001", "2002", "2003", "2004", "2005" }));
        boxNam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                boxNamActionPerformed(evt);
            }
        });

        jLabel17.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel17.setText("Năm");

        inputNumPhone.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputNumPhone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputNumPhoneActionPerformed(evt);
            }
        });
        inputNumPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                inputNumPhoneKeyPressed(evt);
            }
        });

        jLabel7.setBackground(new java.awt.Color(102, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("Nhập số điện thoại:");

        jLabel8.setBackground(new java.awt.Color(102, 255, 255));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Nhập địa chỉ:");

        inputAddress.setToolTipText("");
        inputAddress.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        inputAddress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inputAddressActionPerformed(evt);
            }
        });

        jTableTTNV.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jTableTTNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Loại NV", "Mã NV", "Họ Và Tên", "Ngày Sinh", "Số Điện Thoại", "Địa Chỉ"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, true, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableTTNV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableTTNVMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableTTNV);
        if (jTableTTNV.getColumnModel().getColumnCount() > 0) {
            jTableTTNV.getColumnModel().getColumn(2).setResizable(false);
            jTableTTNV.getColumnModel().getColumn(2).setPreferredWidth(300);
        }

        jButton1.setBackground(new java.awt.Color(102, 102, 102));
        jButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButtonUpdate.setBackground(new java.awt.Color(102, 102, 102));
        jButtonUpdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonUpdate.setForeground(new java.awt.Color(255, 255, 255));
        jButtonUpdate.setText("Sửa");
        jButtonUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUpdateActionPerformed(evt);
            }
        });

        jButtonDelete.setBackground(new java.awt.Color(102, 102, 102));
        jButtonDelete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButtonDelete.setForeground(new java.awt.Color(255, 255, 255));
        jButtonDelete.setText("Xóa");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(296, 296, 296)
                .addComponent(Exit1)
                .addGap(21, 21, 21))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGap(36, 36, 36)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(BoxMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 116, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel16))
                        .addGap(29, 29, 29)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(boxNam, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel17)))
                    .addComponent(inputNumPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 254, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(140, 140, 140)
                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(140, 140, 140)
                .addComponent(jButtonUpdate, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(304, 304, 304))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1014, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(171, 171, 171)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(BoxMaCV, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Exit1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(inputNumPhone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel17)
                                    .addComponent(jLabel16)
                                    .addComponent(jLabel15))
                                .addGap(2, 2, 2)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(boxNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxThang, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(boxNam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel6)
                                    .addComponent(inputMa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(37, 37, 37)
                                .addComponent(jLabel7)))))
                .addGap(38, 38, 38)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inputAddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(inputName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 38, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUpdate))
                .addGap(23, 23, 23))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
//    private String chuyendoiBuoi(String Buoi){
//        String buoi = "";
//        switch (Buoi){
//            case "Sáng": {
//                buoi = "S";
//                break;
//            }
//            case "Chiều":{
//                buoi = "C";
//                break;
//            }
//            case "Tối":{
//                buoi = "T";
//                break;
//            }
//        }
//        return buoi;
//    }
    private boolean laNamNhuan(int Nam){
        if((Nam % 4 == 0 && Nam % 100 != 0) || Nam % 400 == 0)
            return true;
        else return false;
    }
    
    int tinhSoNgay(int thang, int nam){
        int  songay = 0;
        switch(thang){
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                songay = 31;
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                songay = 30;
                break;
            case 2:{
                if(laNamNhuan(nam)) songay = 29;
                else songay = 28;
                break;
            }
        }
        return songay;
    }
    //kiem tra ngya hop le
    private boolean laNgayHopLe(int nDay, int nMonth, int nYear){
	// Kiểm tra năm
	if (nYear < 0){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra tháng
	if (nMonth < 1 || nMonth > 12){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra ngày
        if (nDay < 1 || nDay > tinhSoNgay(nMonth, nYear)){
            return false; // Ngày không còn hợp lệ nữa!
	}
	return true; // Trả về trạng thái cuối cùng...
    }
    
    //reset 
    private void reset(){
        inputMa.setText("");
        BoxMaCV.setSelectedIndex(0);
        inputName.setText("");
        boxNgay.setSelectedIndex(0);
        boxThang.setSelectedIndex(0);
        boxNam.setSelectedIndex(0);
        inputNumPhone.setText("");
        inputAddress.setText("");
    } 
        
//    private boolean SauNgayHienTai(int ngay, int thang, int nam){
//       Calendar c = Calendar.getInstance(); 
//  
//        // set Month 
//        // MONTH starts with 0 i.e. ( 0 - Jan) 
//        c.set(Calendar.MONTH, (thang-1)); 
//  
//        // set Date 
//        c.set(Calendar.DATE, ngay); 
//  
//        // set Year 
//        c.set(Calendar.YEAR, nam); 
//  
//        // creating a date object with specified time. 
//        Date dateOne = c.getTime(); 
//  
//        // creating a date of object 
//        // storing the current date 
//        Date currentDate = new Date(); 
//  
//        //System.out.print("Is currentDate after date one : "); 
//  
//        // if currentDate is after dateOne 
//        //System.out.println(currentDate.after(dateOne));
//        return currentDate.after(dateOne);
//    }    
    private String chucvu(String cv){
        String CV = "";
        switch (cv){
            case "Trưởng Phòng": {CV =  "TN"; break;}
            case "Nhân Viên" : {CV =  "PC"; break;}
            case "Thực Tập": {CV =  "LC"; break;}
            case "Nhân Viên Lâu Năm" : {CV =  "PV"; break;}
        }
        return CV;
    }
    
    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void inputMaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputMaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputMaActionPerformed

    private void inputMaKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputMaKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            inputMa.setEditable(false);
        } else {
            inputMa.setEditable(true);
        }
    }//GEN-LAST:event_inputMaKeyPressed

    private void BoxMaCVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BoxMaCVActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BoxMaCVActionPerformed

    private void inputNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNameActionPerformed

    private void inputNameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNameKeyPressed

    }//GEN-LAST:event_inputNameKeyPressed

    private void boxNgayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNgayActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNgayActionPerformed

    private void boxThangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxThangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxThangActionPerformed

    private void boxNamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_boxNamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_boxNamActionPerformed

    private void inputNumPhoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputNumPhoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputNumPhoneActionPerformed

    private void inputNumPhoneKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_inputNumPhoneKeyPressed
        // TODO add your handling code here:
        char c = evt.getKeyChar();
        if (Character.isLetter(c)) {
            inputNumPhone.setEditable(false);
        } else {
            inputNumPhone.setEditable(true);
        }
    }//GEN-LAST:event_inputNumPhoneKeyPressed

    private void inputAddressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inputAddressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_inputAddressActionPerformed

    private void jTableTTNVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableTTNVMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();

        String manv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 1).toString();
        String macv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 0).toString();
        if(macv.equals("LC")){
            macv = "Thực Tập";
        }else if(macv.equals("PC")){
            macv = "Nhân Viên";
        }else if(macv.equals("PV")){
            macv = "Nhân Viên Lâu Năm";
        }else{
            macv = "Trưởng Phòng";
        }
        String tennv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 2).toString();
        String ngaysinh = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 3).toString();
        String NS[] = ngaysinh.split("/");
        String sodt = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 4).toString();
        String diachi = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 5).toString();

        inputMa.setText(manv);
        BoxMaCV.setSelectedItem(macv);
        inputName.setText(tennv);
        boxNgay.setSelectedItem(NS[0]);
        boxThang.setSelectedItem(NS[1]);
        boxNam.setSelectedItem(NS[2]);
        inputNumPhone.setText(sodt);
        inputAddress.setText(diachi);
    }//GEN-LAST:event_jTableTTNVMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement insert;
        Connection con1;
        ResultSet rs1;

        String manv = String.valueOf(inputMa.getText()).trim();
        String CV = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        String macv = chucvu(CV);
        String tennv = String.valueOf(inputName.getText()).trim();
        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        String NgayThang = nam+"-"+thang+"-"+ngay;
        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        String diachi = String.valueOf(inputAddress.getText()).trim();

                if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        } else if (laNgayHopLe(Integer.parseInt(ngay), Integer.parseInt(thang), Integer.parseInt(nam)) == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày sinh không hợp lệ! Yêu cầu chọn ngày sinh lại!", "Erro", 1);
        } else {
            //Thêm thông tin vào database.
            try {
                Class.forName("com.mysql.jdbc.Driver");
                con = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                insert = con.prepareStatement("SELECT ma_nv  FROM `nhanvien` WHERE ma_nv=?");
               
                insert.setString(1, manv);
                ResultSet rs_checkid = insert.executeQuery();
                                while (rs_checkid.next()) {
                    String ma = rs_checkid.getString("ma_nv");
                    if (ma.equals(manv)) {
                        JOptionPane.showMessageDialog(rootPane, "Mã nhân viên đã trùng! Yêu cầu nhập mã lại", "Erro", 1);
                    }
                }
                } catch (Exception e) {
                e.printStackTrace();
                }
                    
                            try {
                                // TODO add your handling code here:
                                Class.forName("com.mysql.jdbc.Driver");
                                con = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                                insert = con.prepareStatement("insert into nhanvien(ma_nv,ma_cv,ten_nv,ngaysinh,sodt,diachi,trangthai)values(?,?,?,?,?,?,0)");
            
                                insert.setString(1, manv);
                                insert.setString(2, macv);
                                insert.setString(3, tennv);
                                insert.setString(4, NgayThang);
                                insert.setString(5, sodt);
                                insert.setString(6, diachi);

                                insert.executeUpdate();
                                JOptionPane.showMessageDialog(rootPane, "Thêm Nhân Viên Thành Công");
                                HienThiTTNV();
                                reset();


                                } catch (ClassNotFoundException ex) {
                                    Logger.getLogger(AddCa.class.getName()).log(Level.SEVERE, null, ex);
                                } catch (SQLException ex) {
                                    Logger.getLogger(AddCa.class.getName()).log(Level.SEVERE, null, ex);
                                }
                    
    
                

        

        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        //        Connection conn = (Connection) connection.ConnectMySQL();
        //        //lay du lieu tu bang
        //        String manv = String.valueOf(inputMa.getText()).trim();
        //        String macv = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        //        String tennv = String.valueOf(inputName.getText()).trim();
        //        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        //        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        //        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        //        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        //        String diachi = String.valueOf(inputAddress.getText()).trim();
        //
        //        if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            //            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            //            JOptionPane.showMessageDialog(rootPane, "Bận cần  xóa nhân viên nào ?", "Erro", 1);
            //        } else {
            //            try {
                //                DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();
                //                String getmanv = tableModel.getValueAt(jTableTTNV.getSelectedRow(), 1).toString();
                //                CallableStatement cStmt = (CallableStatement) conn.prepareCall("DELETE FROM `nhanvien` WHERE ma_nv=?");
                //                cStmt.setString(1, getmanv);
                //                int a = JOptionPane.showConfirmDialog(rootPane, "Bạn Có Chắc xóa nhân viên này chứ ?");
                //                if (a == JOptionPane.YES_OPTION) {
                    //                    ResultSet rs = cStmt.executeQuery();
                    //                    reset();
                    //                    HienThiTTNV();
                    //                }
                //            } catch (Exception e) {
                //                e.printStackTrace();
                //            }
            //        }

        DefaultTableModel model = (DefaultTableModel) jTableTTNV.getModel();
        int selectedIndex = jTableTTNV.getSelectedRow();

        try {
            Connection con1;
            PreparedStatement insert;

            String getmanv = (String) jTableTTNV.getValueAt(selectedIndex, 1);

            //int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog (rootPane, "Bạn Có Chắc xóa nhân viên này chứ ?","Cảnh Báo",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                // Saving code here

                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                insert = con1.prepareStatement("DELETE FROM `nhanvien` WHERE ma_nv=?");

                insert.setString(1,getmanv);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Xóa nhân viên thành công");
                //                reset();
                HienThiTTNV();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(XoaCa.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(XoaCa.class.getName()).log(Level.SEVERE, null, ex);
        }

        HienThiTTNV();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUpdateActionPerformed
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        //lay du lieu tu bang
        String manv = String.valueOf(inputMa.getText()).trim();
        String CV = String.valueOf(BoxMaCV.getSelectedItem().toString().trim());
        String macv = chucvu(CV);
        String tennv = String.valueOf(inputName.getText()).trim();
        String ngay = String.valueOf(boxNgay.getSelectedItem().toString().trim());
        String thang = String.valueOf(boxThang.getSelectedItem().toString().trim());
        String nam = String.valueOf(boxNam.getSelectedItem().toString().trim());
        String NgayThang = nam+"-"+thang+"-"+ngay;
        String sodt = String.valueOf(inputNumPhone.getText()).trim();
        String diachi = String.valueOf(inputAddress.getText()).trim();
        /*
        Kiểm tra xem các trường có trống hay không nếu có thì thông báo lỗi.
        */
        if (manv.equals("") || macv.equals("") || tennv.equals("") || ngay.equals("")
            || thang.equals("") || nam.equals("") || sodt.equals("") || diachi.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        } else {
            //Thêm thông tin vào database.
            try {
                //                CallableStatement cStmt = (CallableStatement) conn.prepareCall("update nhanvien set ma_cv=? ,ten_nv=? , ngaysinh= ? ,sodt=? , diachi= ? where ma_nv= ?");
                //                cStmt.setString(1, manv);
                //                cStmt.setString(2, macv);
                //                cStmt.setString(3, tennv);
                //                cStmt.setString(4, NgayThang);
                //                cStmt.setString(5, sodt);
                //                cStmt.setString(6, diachi);

                //                ResultSet rs = cStmt.executeQuery();

                Connection con1;
                PreparedStatement insert;
                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                insert = con1.prepareStatement("update nhanvien set ma_cv=? ,ten_nv=? , ngaysinh= ? ,sodt=? , diachi= ? where ma_nv= ?");

                insert.setString(1,macv);
                insert.setString(2,tennv);
                insert.setString(3,NgayThang);
                insert.setString(4,sodt);
                insert.setString(5,diachi);
                insert.setString(6,manv);

                insert.executeUpdate();
                JOptionPane.showMessageDialog(rootPane, "Cập Nhật Nhân Viên Thành Công");

                HienThiTTNV();
                reset();
            } catch (Exception e) {
                e.getStackTrace();
            }
        }
    }//GEN-LAST:event_jButtonUpdateActionPerformed
    
    private void HienThiTTNV() {
        DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = null;
            cStmt = (CallableStatement) conn.prepareCall("SELECT ma_nv,ma_cv,ten_nv,ngaysinh,sodt,diachi FROM `nhanvien` WHERE trangthai=0;");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("ma_nv");
                String macv = rs.getString("ma_cv");
                String tennv = rs.getString("ten_nv");
                String dateNS = rs.getString("ngaysinh");
                String NS[] = dateNS.split("-");
                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
                String sodt = rs.getString("sodt");
                String diachi = rs.getString("diachi");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemNV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemNV().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> BoxMaCV;
    private javax.swing.JButton Exit1;
    private javax.swing.JComboBox<String> boxNam;
    private javax.swing.JComboBox<String> boxNgay;
    private javax.swing.JComboBox<String> boxThang;
    private javax.swing.JFormattedTextField inputAddress;
    private javax.swing.JFormattedTextField inputMa;
    private javax.swing.JFormattedTextField inputName;
    private javax.swing.JFormattedTextField inputNumPhone;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonUpdate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableTTNV;
    // End of variables declaration//GEN-END:variables
}
