/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;
import Connect.MySQLConnection;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.awt.Desktop;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.Row;
import org.apache.poi.ss.usermodel.Sheet;
import org.apache.poi.ss.usermodel.Workbook;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author MSI-VN
 */
public class TinhLuong extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public TinhLuong() {
        initComponents();
//        tableModel = (DefaultTableModel)DS_CaLam.getModel();
//        tableModel = (DefaultTableModel) jTableTTNV.getModel();
//        HienThiTTNV();
        
        LuongNhanVien();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Exit1 = new javax.swing.JButton();
        jLabel24 = new javax.swing.JLabel();
        jFormattedTextField_L_Find = new javax.swing.JFormattedTextField();
        jLabel14 = new javax.swing.JLabel();
        jComboBox_L_Loai = new javax.swing.JComboBox<>();
        jComboBox_sapxepluong = new javax.swing.JComboBox<>();
        jLabel19 = new javax.swing.JLabel();
        TinhLuong_ = new javax.swing.JButton();
        Tu_Nam = new javax.swing.JComboBox<>();
        Tu_T = new javax.swing.JComboBox<>();
        Tu_N = new javax.swing.JComboBox<>();
        jLabel21 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        Den_N = new javax.swing.JComboBox<>();
        Den_T = new javax.swing.JComboBox<>();
        Den_Nam = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        Table_LuongNV = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(204, 0, 153));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("TÍNH LƯƠNG");

        Exit1.setBackground(new java.awt.Color(255, 51, 51));
        Exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        jLabel24.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel24.setText("TÌM NHÂN VIÊN:");

        jFormattedTextField_L_Find.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jFormattedTextField_L_Find.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextField_L_FindActionPerformed(evt);
            }
        });
        jFormattedTextField_L_Find.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jFormattedTextField_L_FindKeyReleased(evt);
            }
        });

        jLabel14.setBackground(new java.awt.Color(0, 0, 0));
        jLabel14.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel14.setText("XEM THEO CHỨC VỤ:");

        jComboBox_L_Loai.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_L_Loai.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Trưởng Phòng", "Nhân Viên", "Nhân Viên Lâu Năm", "Thực Tập" }));
        jComboBox_L_Loai.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_L_LoaiActionPerformed(evt);
            }
        });

        jComboBox_sapxepluong.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jComboBox_sapxepluong.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lương Tăng Dần", "Lương Giảm Dần" }));
        jComboBox_sapxepluong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_sapxepluongActionPerformed(evt);
            }
        });

        jLabel19.setBackground(new java.awt.Color(0, 0, 0));
        jLabel19.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel19.setText("SẮP XẾP THEO: ");

        TinhLuong_.setBackground(new java.awt.Color(255, 255, 255));
        TinhLuong_.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TinhLuong_.setText("Tính Lương");
        TinhLuong_.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TinhLuong_ActionPerformed(evt);
            }
        });

        Tu_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tu_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023" }));
        Tu_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Tu_NamActionPerformed(evt);
            }
        });

        Tu_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tu_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Tu_T.setPreferredSize(new java.awt.Dimension(60, 22));

        Tu_N.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Tu_N.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Tu_N.setPreferredSize(new java.awt.Dimension(60, 22));

        jLabel21.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel21.setText("Ngày:");

        jLabel25.setBackground(new java.awt.Color(0, 0, 0));
        jLabel25.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel25.setText("TỪ:");

        jLabel20.setBackground(new java.awt.Color(0, 0, 0));
        jLabel20.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel20.setText("TÍNH LƯƠNG BẮT ĐẦU");

        jLabel22.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel22.setText("Tháng:");

        jLabel23.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel23.setText("Năm");

        jLabel29.setBackground(new java.awt.Color(0, 0, 0));
        jLabel29.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel29.setText("ĐẾN");

        Den_N.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Den_N.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));
        Den_N.setPreferredSize(new java.awt.Dimension(60, 22));

        Den_T.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Den_T.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "01", "02", "03", "04", "05", "06", "07", "08", "09", "10", "11", "12" }));
        Den_T.setPreferredSize(new java.awt.Dimension(60, 22));

        Den_Nam.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Den_Nam.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2021", "2022", "2023" }));
        Den_Nam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Den_NamActionPerformed(evt);
            }
        });

        Table_LuongNV.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        Table_LuongNV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Mã NV", "Tên NV", "Chức Vụ", "Đơn Giá", "Số Ca", "Lương"
            }
        ));
        jScrollPane3.setViewportView(Table_LuongNV);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(51, 51, 51));
        jButton1.setText("Xuất Thống Kê");
        jButton1.setBorderPainted(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane3)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jLabel1)
                                .addGap(424, 424, 424)
                                .addComponent(Exit1))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(198, 198, 198)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel25)
                                            .addComponent(jLabel29)))
                                    .addComponent(jLabel20))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel21)
                                        .addGap(55, 55, 55)
                                        .addComponent(jLabel22))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Tu_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Tu_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(Den_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(Den_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(26, 26, 26)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(Den_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(Tu_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(jLabel23)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(75, 75, 75)
                                .addComponent(jLabel24)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jFormattedTextField_L_Find, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 12, Short.MAX_VALUE)
                        .addComponent(TinhLuong_)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 94, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox_L_Loai, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_sapxepluong, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(485, 485, 485)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Exit1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFormattedTextField_L_Find, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel24))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel20)
                    .addComponent(jLabel21)
                    .addComponent(jLabel22)
                    .addComponent(jLabel23))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(jComboBox_L_Loai, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(jComboBox_sapxepluong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(TinhLuong_, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Tu_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tu_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Tu_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel25))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(Den_N, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Den_T, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(Den_Nam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel29)))))
                .addGap(19, 19, 19)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(56, 56, 56))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents
    public void openFile(String file){
        try{
            File path = new File(file);
            Desktop.getDesktop().open(path);
        }catch(IOException ioe){
            System.out.println(ioe);
        }
    }
    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void jFormattedTextField_L_FindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextField_L_FindActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextField_L_FindActionPerformed

    private void jFormattedTextField_L_FindKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jFormattedTextField_L_FindKeyReleased
        // TODO add your handling code here:
        Connection conn = (Connection) connection.ConnectMySQL();
        tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        ResultSet rs = null;
        String input = null;
        try {
            input = String.valueOf(jFormattedTextField_L_Find.getText());
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("select soca.nv as 'manv', soca.ten as 'tennv', cv.ma_cv as 'cv',\n" +
                "					cv.hesoluong as 'dongia', soca.sc as 'soca', soca.sc*cv.hesoluong as 'luong'\n" +
                "		from chucvu cv, (select cl.ma_nv nv , nv.ma_cv cv, count(cl.ma_calam) sc, nv.ten_nv ten \n" +
                "						from calam cl, nhanvien nv\n" +
                "						where cl.ma_nv = nv.ma_nv and nv.ma_nv=?\n" +
                "						group by cl.ma_nv) soca\n" +
                "		where cv.ma_cv = soca.cv \n" +
                "		order by soca.nv;");
            cStmt.setString(1, input);
            rs = cStmt.executeQuery();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                tableModel.addRow(new String[]{manv, tennv, cv, dongia, sc, luong});
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(rootPane, "Không có thông tin nhân viên bạn cần tìm", "ERROR", 1);
        }
    }//GEN-LAST:event_jFormattedTextField_L_FindKeyReleased

    private void jComboBox_L_LoaiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_L_LoaiActionPerformed
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        String chucvu = String.valueOf(jComboBox_L_Loai.getSelectedItem()).toString().trim();
        String CV = chucvu(chucvu);
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("select soca.nv as 'manv', soca.ten as 'tennv', cv.ma_cv as 'cv',\n" +
                "					cv.hesoluong as 'dongia', soca.sc as 'soca', soca.sc*cv.hesoluong as 'luong'\n" +
                "		from chucvu cv, (select cl.ma_nv nv , nv.ma_cv cv, count(cl.ma_calam) sc, nv.ten_nv ten \n" +
                "						from calam cl, nhanvien nv\n" +
                "						where cl.ma_nv = nv.ma_nv \n" +
                "						group by cl.ma_nv) soca\n" +
                "		where cv.ma_cv = soca.cv and cv.ma_cv=?\n" +
                "		order by soca.nv;");
            cStmt.setString(1, CV);
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                tableModel.addRow(new String[]{manv, tennv, cv, dongia, sc, luong});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_L_LoaiActionPerformed

    private void jComboBox_sapxepluongActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_sapxepluongActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        String luachon = String.valueOf(jComboBox_sapxepluong.getSelectedItem()).toString().trim();
        try {
            CallableStatement cStmt = null;
            if(luachon.equals("Lương Tăng Dần")){
                cStmt = (CallableStatement) conn.prepareCall("select soca.nv as 'manv', soca.ten as 'tennv', cv.ma_cv as 'cv', cv.hesoluong as 'dongia', soca.sc as 'soca', soca.sc*cv.hesoluong as 'luong' \n" +
                    "	from chucvu cv, (select cl.ma_nv nv , nv.ma_cv cv, count(cl.ma_calam) sc, nv.ten_nv ten\n" +
                    "                 from calam cl, nhanvien nv where cl.ma_nv = nv.ma_nv group by cl.ma_nv) soca \n" +
                    "                 where cv.ma_cv = soca.cv \n" +
                    "                 ORDER BY `luong` ASC");

            }else if(luachon.equals("Lương Giảm Dần")){
                cStmt = (CallableStatement) conn.prepareCall("select soca.nv as 'manv', soca.ten as 'tennv', cv.ma_cv as 'cv', cv.hesoluong as 'dongia', soca.sc as 'soca', soca.sc*cv.hesoluong as 'luong' \n" +
                    "	from chucvu cv, (select cl.ma_nv nv , nv.ma_cv cv, count(cl.ma_calam) sc, nv.ten_nv ten\n" +
                    "                 from calam cl, nhanvien nv where cl.ma_nv = nv.ma_nv group by cl.ma_nv) soca \n" +
                    "                 where cv.ma_cv = soca.cv \n" +
                    "                 ORDER BY `luong` DESC");
            }
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                tableModel.addRow(new String[]{manv, tennv, cv, dongia, sc, luong});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jComboBox_sapxepluongActionPerformed

    private void TinhLuong_ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TinhLuong_ActionPerformed
        // TODO add your handling code here:
        //lay du lieu tu ngay nao do
        String Tu_ngay = String.valueOf(Tu_N.getSelectedItem().toString().trim());
        String Tu_thang = String.valueOf(Tu_T.getSelectedItem().toString().trim());
        String Tu_nam = String.valueOf(Tu_Nam.getSelectedItem().toString().trim());
        //den ngay nao do
        String Den_ngay = String.valueOf(Den_N.getSelectedItem().toString().trim());
        String Den_thang = String.valueOf(Den_T.getSelectedItem().toString().trim());
        String Den_nam = String.valueOf(Den_Nam.getSelectedItem().toString().trim());
        //dinh dang ngay;
        String NgayThang_TU = Tu_nam + "-" + Tu_thang + "-" + Tu_ngay;
        String NgayThang_DEN = Den_nam + "-" + Den_thang + "-" + Den_ngay;

        int kiemtra_tungay_nhohon_denngay = NgayThang_TU.compareTo(NgayThang_DEN);

//        boolean chekcdateTu = SauNgayHienTai(Integer.parseInt(Tu_ngay), Integer.parseInt(Tu_thang), Integer.parseInt(Tu_nam));
//        boolean chekcdateDen = SauNgayHienTai(Integer.parseInt(Den_ngay), Integer.parseInt(Den_thang), Integer.parseInt(Den_nam));
        boolean hopleDateTu = laNgayHopLe(Integer.parseInt(Tu_ngay), Integer.parseInt(Tu_thang), Integer.parseInt(Tu_nam));
        boolean hopleDateDen = laNgayHopLe(Integer.parseInt(Den_ngay), Integer.parseInt(Den_thang), Integer.parseInt(Den_nam));

        if (hopleDateTu == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Bắt Đầu Không Hợp Lệ!!", "Lỗi Không Hợp Lệ", 1);
        } else if (hopleDateDen == false) {
            JOptionPane.showMessageDialog(rootPane, "Ngày Kết Thúc Không Hợp Lệ!!", "Lỗi Không Hợp Lệ", 1);
        } else if (kiemtra_tungay_nhohon_denngay > 0) {
            JOptionPane.showMessageDialog(rootPane, "Warning:Ngày Bắt Đầu <Ngày Kết Thúc", "Lỗi Không Hợp Lệ", 1);
//        } else if (chekcdateTu == false) {
//            JOptionPane.showMessageDialog(rootPane, "Ngày Tính lương không hợp lê (Các Ngày Phải Sau Ngày Hiện Tại)", "Erro", 1);
//        } else if (chekcdateDen == false) {
//            JOptionPane.showMessageDialog(rootPane, "Ngày Tính Lương Phải Nhỏ Hơn Ngày Hiện tại", "Lỗi Không Hợp Lệ", 1);
        }else {
        try {
            Connection conn = connection.ConnectMySQL();
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("{call tinhluongnhanvien(?,?)}");
            cStmt.setString(1, NgayThang_TU);
            cStmt.setString(2,NgayThang_DEN);
            ResultSet rs = cStmt.executeQuery();
            tableModel = (DefaultTableModel) Table_LuongNV.getModel();
            tableModel.setRowCount(0);
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                tableModel = (DefaultTableModel) Table_LuongNV.getModel();
                tableModel.addRow(new String[]{manv, tennv, cv, dongia, sc, luong});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
        }
    }//GEN-LAST:event_TinhLuong_ActionPerformed

    private void Tu_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Tu_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Tu_NamActionPerformed

    private void Den_NamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Den_NamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Den_NamActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
                    try{
                        JFileChooser jFileChooser = new JFileChooser();
                        jFileChooser.showSaveDialog(this);
                        File saveFile = jFileChooser.getSelectedFile();

                        if(saveFile != null){
                            saveFile = new File(saveFile.toString()+".xlsx");
                            Workbook wb = new XSSFWorkbook();
                            Sheet sheet = wb.createSheet("Quản Lý Nhân Sự");

                            Row rowCol = sheet.createRow(0);
                            for(int i=0;i<Table_LuongNV.getColumnCount();i++){
                                Cell cell = rowCol.createCell(i);
                                cell.setCellValue(Table_LuongNV.getColumnName(i));
                            }

                            for(int j=0;j<Table_LuongNV.getRowCount();j++){
                                Row row = sheet.createRow(j+1);
                                for(int k=0;k<Table_LuongNV.getColumnCount();k++){
                                    Cell cell = row.createCell(k);
                                    if(Table_LuongNV.getValueAt(j, k)!=null){
                                        cell.setCellValue(Table_LuongNV.getValueAt(j, k).toString());
                                    }
                                }
                            }
                            FileOutputStream out = new FileOutputStream(new File(saveFile.toString()));
                            wb.write(out);
                            wb.close();
                            out.close();
                            openFile(saveFile.toString());
                        }else{
                            JOptionPane.showMessageDialog(null,"Thao Tác In Đã Hủy");
                        }
                }catch(FileNotFoundException e){
                    System.out.println(e);
                }catch(IOException io){
                    System.out.println(io);
                }
    }//GEN-LAST:event_jButton1ActionPerformed
//    private String chuyendoiBuoi(String Buoi){
//        String buoi = "";
//        switch (Buoi){
//            case "Sáng": {
//                buoi = "S";
//                break;
//            }
//            case "Chiều":{
//                buoi = "C";
//                break;
//            }
//            case "Tối":{
//                buoi = "T";
//                break;
//            }
//        }
//        return buoi;
//    }
    private boolean laNamNhuan(int Nam){
        if((Nam % 4 == 0 && Nam % 100 != 0) || Nam % 400 == 0)
            return true;
        else return false;
    }
    
    int tinhSoNgay(int thang, int nam){
        int  songay = 0;
        switch(thang){
            case 1:
            case 3:
            case 5:
            case 7:
            case 8:
            case 10:
            case 12:
                songay = 31;
                break;
            case 4:
            case 6:
            case 9:
            case 11:
                songay = 30;
                break;
            case 2:{
                if(laNamNhuan(nam)) songay = 29;
                else songay = 28;
                break;
            }
        }
        return songay;
    }
//    //kiem tra ngya hop le
    private boolean laNgayHopLe(int nDay, int nMonth, int nYear){
	// Kiểm tra năm
	if (nYear < 0){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra tháng
	if (nMonth < 1 || nMonth > 12){
            return false; // Ngày không còn hợp lệ nữa!
	}
	// Kiểm tra ngày
        if (nDay < 1 || nDay > tinhSoNgay(nMonth, nYear)){
            return false; // Ngày không còn hợp lệ nữa!
	}
	return true; // Trả về trạng thái cuối cùng...
    }
    
    //reset 
//    private void reset(){
//        inputMa.setText("");
//        BoxMaCV.setSelectedIndex(0);
//        inputName.setText("");
//        boxNgay.setSelectedIndex(0);
//        boxThang.setSelectedIndex(0);
//        boxNam.setSelectedIndex(0);
//        inputNumPhone.setText("");
//        inputAddress.setText("");
//    } 
        
    private boolean SauNgayHienTai(int ngay, int thang, int nam){
       Calendar c = Calendar.getInstance(); 
  
        // set Month 
        // MONTH starts with 0 i.e. ( 0 - Jan) 
        c.set(Calendar.MONTH, (thang-1)); 
  
        // set Date 
        c.set(Calendar.DATE, ngay); 
  
        // set Year 
        c.set(Calendar.YEAR, nam); 
  
        // creating a date object with specified time. 
        Date dateOne = c.getTime(); 
  
        // creating a date of object 
        // storing the current date 
        Date currentDate = new Date(); 
  
        //System.out.print("Is currentDate after date one : "); 
  
        // if currentDate is after dateOne 
        //System.out.println(currentDate.after(dateOne));
        return currentDate.after(dateOne);
    } 
    public void LuongNhanVien() {
        DefaultTableModel tableModel = (DefaultTableModel) Table_LuongNV.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("select soca.nv as 'manv', soca.ten as 'tennv', cv.ma_cv as 'cv',\n" +
"					cv.hesoluong as 'dongia', soca.sc as 'soca', soca.sc*cv.hesoluong as 'luong'\n" +
"		from chucvu cv, (select cl.ma_nv nv , nv.ma_cv cv, count(cl.ma_calam) sc, nv.ten_nv ten \n" +
"						from calam cl, nhanvien nv\n" +
"						where cl.ma_nv = nv.ma_nv \n" +
"						group by cl.ma_nv) soca\n" +
"		where cv.ma_cv = soca.cv \n" +
"		order by soca.nv;");
            ResultSet rs = cStmt.executeQuery();
            while (rs.next()) {
                String manv = rs.getString("manv");
                String tennv = rs.getString("tennv");
                String cv = rs.getString("cv");
                String dongia = rs.getString("dongia");
                String sc = rs.getString("soca");
                String luong = rs.getString("luong");
                tableModel.addRow(new String[]{manv, tennv, cv, dongia, sc, luong});
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    
    private String chucvu(String cv){
        String CV = "";
        switch (cv){
//            case "Thu Ngân": {CV =  "TN"; break;}
//            case "Pha Chế" : {CV =  "PC"; break;}
//            case "Lao Công": {CV =  "LC"; break;}
//            case "Phục Vụ" : {CV =  "PV"; break;}
            case "Trưởng Phòng": {CV =  "TN"; break;}
            case "Nhân Viên" : {CV =  "PC"; break;}
            case "Thực Tập": {CV =  "LC"; break;}
            case "Nhân Viên Lâu Năm" : {CV =  "PV"; break;}
        }
        return CV;
    }
        
//    private void HienThiTTNV() {
//        DefaultTableModel tableModel = (DefaultTableModel) jTableTTNV.getModel();
//        tableModel.setRowCount(0);
//        Connection conn = connection.ConnectMySQL();
//        try {
//            CallableStatement cStmt = null;
//            cStmt = (CallableStatement) conn.prepareCall("SELECT ma_nv,ma_cv,ten_nv,ngaysinh,sodt,diachi FROM `nhanvien`;");
//            ResultSet rs = cStmt.executeQuery();
//            while (rs.next()) {
//                String manv = rs.getString("ma_nv");
//                String macv = rs.getString("ma_cv");
//                String tennv = rs.getString("ten_nv");
//                String dateNS = rs.getString("ngaysinh");
//                String NS[] = dateNS.split("-");
//                String ngaysinh = NS[2] + "/" + NS[1] + "/" + NS[0];
//                String sodt = rs.getString("sodt");
//                String diachi = rs.getString("diachi");
//                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
//                tableModel.addRow(new String[]{macv, manv, tennv, ngaysinh, sodt, diachi});
//            }
//        } catch (Exception e) {
//            e.printStackTrace();
//        }
//    }
    
    
    


    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TinhLuong.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TinhLuong().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> Den_N;
    private javax.swing.JComboBox<String> Den_Nam;
    private javax.swing.JComboBox<String> Den_T;
    private javax.swing.JButton Exit1;
    private javax.swing.JTable Table_LuongNV;
    private javax.swing.JButton TinhLuong_;
    private javax.swing.JComboBox<String> Tu_N;
    private javax.swing.JComboBox<String> Tu_Nam;
    private javax.swing.JComboBox<String> Tu_T;
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox_L_Loai;
    private javax.swing.JComboBox<String> jComboBox_sapxepluong;
    private javax.swing.JFormattedTextField jFormattedTextField_L_Find;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables
}
