/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Giaodien;
import Connect.MySQLConnection;
import com.mysql.jdbc.CallableStatement;
import java.util.Calendar;
import java.util.Date;
import com.mysql.jdbc.Statement;
import java.sql.ResultSet;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author MSI-VN
 */
public class User1 extends javax.swing.JFrame {

    /**
     * Creates new form AddCa
     */
    MySQLConnection connection = new MySQLConnection();
    DefaultTableModel tableModel;
    public User1() {
        initComponents();
        tableModel = (DefaultTableModel)Table_Edit.getModel();
        ShowTC_TTCL();
        txtid.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel9 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtten = new javax.swing.JFormattedTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        Table_Edit = new javax.swing.JTable();
        TC_UPdate = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txtid = new javax.swing.JFormattedTextField();
        Exit1 = new javax.swing.JButton();
        txtuser = new javax.swing.JTextField();
        txtpass = new javax.swing.JTextField();
        TC_Delete = new javax.swing.JButton();
        TC_Add = new javax.swing.JButton();

        jLabel9.setText("jLabel9");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(204, 255, 204));

        jLabel1.setBackground(new java.awt.Color(102, 255, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(153, 0, 0));
        jLabel1.setText("QUẢN LÝ ACCOUNT");

        jLabel2.setBackground(new java.awt.Color(102, 255, 255));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel2.setText("Password:");

        jLabel3.setBackground(new java.awt.Color(102, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel3.setText("Tên:");

        jLabel4.setBackground(new java.awt.Color(102, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("UserName:");

        txtten.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Table_Edit.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        Table_Edit.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Tên", "UserName", "Password"
            }
        ));
        Table_Edit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Table_EditMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(Table_Edit);

        TC_UPdate.setBackground(new java.awt.Color(204, 204, 255));
        TC_UPdate.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TC_UPdate.setText("Sửa ");
        TC_UPdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_UPdateActionPerformed(evt);
            }
        });

        jLabel11.setBackground(new java.awt.Color(102, 255, 255));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel11.setText("ID:");

        txtid.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        Exit1.setBackground(new java.awt.Color(255, 51, 51));
        Exit1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        Exit1.setText("X");
        Exit1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Exit1ActionPerformed(evt);
            }
        });

        txtuser.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        txtpass.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N

        TC_Delete.setBackground(new java.awt.Color(204, 204, 255));
        TC_Delete.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TC_Delete.setText("Xóa");
        TC_Delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_DeleteActionPerformed(evt);
            }
        });

        TC_Add.setBackground(new java.awt.Color(204, 204, 255));
        TC_Add.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        TC_Add.setText("Thêm");
        TC_Add.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TC_AddActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(329, 329, 329)
                        .addComponent(Exit1)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel11))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(TC_Delete, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(41, 41, 41)
                                .addComponent(TC_UPdate, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, 245, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtid, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(68, 68, 68)
                                .addComponent(TC_Add, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 669, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(40, 40, 40))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(Exit1))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(txtid))
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel3)
                                .addComponent(txtten, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(69, 69, 69)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtuser, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(30, 30, 30)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtpass, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))))
                        .addGap(29, 29, 29)
                        .addComponent(TC_Add)
                        .addGap(37, 37, 37)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(TC_UPdate)
                            .addComponent(TC_Delete))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 381, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(37, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

        

    private void TC_UPdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_UPdateActionPerformed
       Connection conn = connection.ConnectMySQL();
        Statement Stmt = null;
        String id = String.valueOf(txtid.getText()).trim();
        String name = String.valueOf(txtten.getText()).trim();
        String user = String.valueOf(txtuser.getText()).trim();
        String pass = String.valueOf(txtpass.getText()).trim();
//        String ngay = String.valueOf(TC_Ngay.getSelectedItem().toString().trim());
//        String thang = String.valueOf(TC_Thang.getSelectedItem().toString().trim());
//        String nam = String.valueOf(TC_Nam.getSelectedItem().toString().trim());
//        String BUOI = String.valueOf(TC_BoxBuoi.getSelectedItem().toString().trim());
//        String buoi = chuyendoiBuoi(BUOI);
//        String ghichu = TC_ghichu.getText();
//        String NgayThang = nam+"-"+thang+"-"+ngay;
//        boolean chekcdate = SauNgayHienTai(Integer.parseInt(ngay) , Integer.parseInt(thang), Integer.parseInt(nam));
        if(id.equals("") || name.equals("")|| user.equals("")|| pass.equals("")){
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin!!!", "Error", 1);
        }else{
            boolean checktrung = true;
            try {

                CallableStatement cSmt1 = (CallableStatement) conn.prepareCall("SELECT `id`, `name`, `tendangnhap`, `matkhau` FROM `dangnhap` where id=? and name=? and tendangnhap=? and matkhau=?");
                cSmt1.setString(1, id);
                cSmt1.setString(2, name);
                cSmt1.setString(3, user);
                cSmt1.setString(4, pass);
                ResultSet rs_checkid = cSmt1.executeQuery();
                if(rs_checkid.next()){
                    JOptionPane.showMessageDialog(rootPane, "Thông tin chưa thay đổi", "Erro", 1);
                    checktrung = false;
                }else{
                    try{
                        
                    Connection con1;
                    PreparedStatement insert;
                    Class.forName("com.mysql.jdbc.Driver");
                    con1 = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                    insert = con1.prepareStatement("update dangnhap set name= ? , tendangnhap=? , matkhau= ?  where id= ?");
                    insert.setString(1,name);
                    insert.setString(2,user);
                    insert.setString(3,pass);
                    insert.setString(4,id);
                    
                    insert.executeUpdate();
                    JOptionPane.showMessageDialog(this, "Cập Nhật Tài Khoản User thành công");
            
                    txtid.setText("");
                    txtten.setText("");
                    txtuser.setText(""); 
                    txtpass.setText(""); 

                    }catch (Exception e) {
                        e.printStackTrace();
                    }
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
        }
        ShowTC_TTCL();
    }//GEN-LAST:event_TC_UPdateActionPerformed

    private void Table_EditMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Table_EditMouseClicked
        // TODO add your handling code here:
        DefaultTableModel tableModel= (DefaultTableModel)Table_Edit.getModel();
        String id = tableModel.getValueAt(Table_Edit.getSelectedRow(), 0).toString();
        String name = tableModel.getValueAt(Table_Edit.getSelectedRow(), 1).toString();
        String user = tableModel.getValueAt(Table_Edit.getSelectedRow(), 2).toString();
        String pass = tableModel.getValueAt(Table_Edit.getSelectedRow(), 3).toString();
        
       
        
        
        txtid.setText(id);
        txtten.setText(name);
        txtuser.setText(user);
        txtpass.setText(pass);
    }//GEN-LAST:event_Table_EditMouseClicked

    private void Exit1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Exit1ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_Exit1ActionPerformed

    private void TC_DeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_DeleteActionPerformed
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) Table_Edit.getModel();
        int selectedIndex = Table_Edit.getSelectedRow();

        try {
            Connection con1;
            PreparedStatement insert;

            String getmanv = (String) Table_Edit.getValueAt(selectedIndex, 0);

            //int id = Integer.parseInt(model.getValueAt(selectedIndex, 0).toString());

            int dialogResult = JOptionPane.showConfirmDialog (rootPane, "Bạn Có Chắc xóa tài khoản này chứ ?","Cảnh Báo",JOptionPane.YES_NO_OPTION);
            if(dialogResult == JOptionPane.YES_OPTION){
                // Saving code here

                Class.forName("com.mysql.jdbc.Driver");
                con1 = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                insert = con1.prepareStatement("DELETE FROM `dangnhap` WHERE id=?");

                insert.setString(1,getmanv);
                insert.executeUpdate();
                JOptionPane.showMessageDialog(this, "Xóa Tài Khoản thành công");
                //                reset();
                ShowTC_TTCL();
            }
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        }

        ShowTC_TTCL();
    }//GEN-LAST:event_TC_DeleteActionPerformed

    private void TC_AddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TC_AddActionPerformed
        // TODO add your handling code here:
        Connection con;
        PreparedStatement insert;
        Connection con1;
        ResultSet rs1;

        String id = String.valueOf(txtid.getText()).trim();
        String name = String.valueOf(txtten.getText()).trim();
        String user = String.valueOf(txtuser.getText()).trim();
        String pass = String.valueOf(txtpass.getText()).trim();
        

                if ( name.equals("") || user.equals("") || pass.equals("")) {
            JOptionPane.showMessageDialog(rootPane, "Yêu cầu nhập đầy đủ thông tin", "Erro", 1);
        }  else {
            //Thêm thông tin vào database.
                try {
                    Class.forName("com.mysql.jdbc.Driver");
                    con = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                    insert = con.prepareStatement("SELECT tendangnhap  FROM `dangnhap` WHERE tendangnhap=? ");
               
                    insert.setString(1, user);
//                    insert.setString(2, pass);
                    ResultSet rs_checkid = insert.executeQuery();
                    while (rs_checkid.next()) {
                        String ma = rs_checkid.getString("tendangnhap");
//                        String pa = rs_checkid.getString("matkhau");
                    if (ma.equals(user) ) {
                        JOptionPane.showMessageDialog(rootPane, "Tài Khoản đã tồn tại! Yêu cầu chọn UserName khác", "Erro", 1);
                    } 
                    }
                }catch (Exception e) {
                e.printStackTrace();
            }
                        try {
                                // TODO add your handling code here:
                                Class.forName("com.mysql.jdbc.Driver");
                                con = DriverManager.getConnection("jdbc:mysql://localhost/doan_dbms","root","");
                                insert = con.prepareStatement("insert into dangnhap(name,tendangnhap,matkhau)values(?,?,?)");
                                insert.setString(1, name);
                                insert.setString(2, user);
                                insert.setString(3, pass);


                                insert.executeUpdate();
                                JOptionPane.showMessageDialog(rootPane, "Thêm Tài Khoản Thành Công");
                                ShowTC_TTCL();
                                txtten.setText("");
                                txtuser.setText("");
                                txtpass.setText("");
        

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(User1.class.getName()).log(Level.SEVERE, null, ex);
        }
                    
                
            
        
        
        }
    }//GEN-LAST:event_TC_AddActionPerformed
    private void ShowTC_TTCL(){
    DefaultTableModel tableModel= (DefaultTableModel)Table_Edit.getModel();
        tableModel.setRowCount(0);
        Connection conn = connection.ConnectMySQL();
        ResultSet rs = null;
        try {
            CallableStatement cStmt = (CallableStatement) conn.prepareCall("SELECT `id`, `name`, `tendangnhap`, `matkhau` FROM `dangnhap`");
            rs = cStmt.executeQuery();
            while(rs.next()){
                String id = rs.getString("id");
                String name = rs.getString("name");
                String tendn = rs.getString("tendangnhap");
                String mk = rs.getString("matkhau");
//                String dateNS = rs.getString("ngaylam");
//                String NS[] = dateNS.split("-");
//                String ngaylam = NS[2]+"/"+NS[1]+"/"+NS[0];
//                String buoi = rs.getString("buoi");
//                String ghichu = rs.getString("ghichu");
                //String ngaysinh = dateNS.getDay()+"/"+dateNS.getMonth()+""+dateNS.getYear();
                tableModel.addRow(new String[]{id, name, tendn, mk});
            } 
        } catch (Exception e) {
            e.printStackTrace();
        }
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User1().setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Exit1;
    private javax.swing.JButton TC_Add;
    private javax.swing.JButton TC_Delete;
    private javax.swing.JButton TC_UPdate;
    private javax.swing.JTable Table_Edit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JFormattedTextField txtid;
    private javax.swing.JTextField txtpass;
    private javax.swing.JFormattedTextField txtten;
    private javax.swing.JTextField txtuser;
    // End of variables declaration//GEN-END:variables
}
